// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteOnepiece.Models.data;

#nullable disable

namespace SiteOnepiece.Migrations
{
    [DbContext(typeof(OnepieceDbContext))]
    [Migration("20240819021417_ajoutSeedParent")]
    partial class ajoutSeedParent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SiteOnepiece.Models.Enfant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstVedette")
                        .HasColumnType("bit");

                    b.Property<int>("IdParent")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomFruitDemon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Prime")
                        .HasColumnType("float");

                    b.Property<int>("ageDebut")
                        .HasColumnType("int");

                    b.Property<int>("agePrensent")
                        .HasColumnType("int");

                    b.Property<string>("typeDeFruit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("IdParent");

                    b.ToTable("Enfants");
                });

            modelBuilder.Entity("SiteOnepiece.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MoyennePrime")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("nombreUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Logia est le nom donné à un type de Fruit du Démon. Il est caractérisé par\r\nle fait qu'il donne à son utilisateur le pouvoir de prendre la forme\r\nd'un élément naturel, de le produire et le contrôler à volonté.",
                            ImageURL = "/images/Suna_Suna_no_Mi_Infobox.jpg",
                            MoyennePrime = 170,
                            Nom = "Logia",
                            nombreUtilisateur = 17
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zoan est le nom donné à un type de Fruit du Démon permettant à son utilisateur de se transformer en animal ou en une créature hybride (moitié espèce animale et moitié espèce de l'utilisateur, souvent humain) à volonté.",
                            ImageURL = "/images/Gomu_Gomu_no_Mi_Infobox.jpg",
                            MoyennePrime = 636,
                            Nom = "Zoan",
                            nombreUtilisateur = 80
                        },
                        new
                        {
                            Id = 3,
                            Description = "Paramecia donnent aux utilisateurs un pouvoir \"surhumain\" qui peut affecter son corps, manipuler l'environnement ou produire une substance quelconque. Modifier. Permet de durcir son corps à volonté et augmenté la température des parties tempérés.",
                            ImageURL = "/images/Ope_Ope_no_Mi_Infobox.jpg",
                            MoyennePrime = 162,
                            Nom = "Paramecia",
                            nombreUtilisateur = 96
                        });
                });

            modelBuilder.Entity("SiteOnepiece.Models.Enfant", b =>
                {
                    b.HasOne("SiteOnepiece.Models.Parent", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SiteOnepiece.Models.Parent", b =>
                {
                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
